<a href="https://colab.research.google.com/github/ibacaraujo/deep-learning-with-pytorch/blob/master/ch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 2

In [0]:
import torch

## 2.1 Tensor fundamentals

In [0]:
a = torch.ones(3)

In [0]:
a

tensor([1., 1., 1.])

In [0]:
a[1]

tensor(1.)

In [0]:
float(a[1])

1.0

In [0]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [0]:
# triangle 2D coordinates
points = torch.zeros(6)
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

In [0]:
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
points

tensor([1., 4., 2., 1., 3., 5.])

In [0]:
# coordinates of the first point
float(points[0]), float(points[1])

(1.0, 4.0)

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [0]:
points.shape

torch.Size([3, 2])

In [0]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [0]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [0]:
points[0, 1]

tensor(4.)

In [0]:
points[0]

tensor([1., 4.])

## 2.2 Tensors and storages

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [0]:
# index into a storage manually
points_storage = points.storage()
points_storage[0]

1.0

In [0]:
points.storage()[1]

4.0

In [0]:
# changing the value of a storage, changes the content of its referring tensor
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

## 2.3 Size, storage offset, and strides

In [3]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()

2

In [4]:
second_point.size()

torch.Size([2])

In [5]:
# The size contains the same information in the shape property
second_point.shape

torch.Size([2])

In [6]:
points.stride()

(2, 1)

In [7]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.size()

torch.Size([2])

In [9]:
second_point.storage_offset()

2

In [10]:
second_point.stride()

(1,)

In [11]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

In [12]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [13]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [14]:
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [15]:
# verify that the two tensors share storage
id(points.storage()) == id(points_t.storage())

True

In [16]:
points.stride()

(2, 1)

In [17]:
points_t.stride()

(1, 2)

In [18]:
# transposing isn't limited to matrices
some_tensor = torch.ones(2, 4, 5)
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor.shape

torch.Size([2, 4, 5])

In [19]:
some_tensor_t.shape

torch.Size([5, 4, 2])

In [20]:
some_tensor.stride()

(20, 5, 1)

In [21]:
some_tensor_t.stride()

(1, 5, 20)

In [22]:
points.is_contiguous()

True

In [23]:
points_t.is_contiguous()

False

In [24]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [25]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [26]:
points_t.stride()

(1, 2)

In [27]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [28]:
points_t_cont.stride()

(3, 1)

In [29]:
points_t_cont.storage()

 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]