<a href="https://colab.research.google.com/github/ibacaraujo/deep-learning-with-pytorch/blob/master/ch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 2

In [0]:
import torch

## 2.1 Tensor fundamentals

In [0]:
a = torch.ones(3)

In [0]:
a

tensor([1., 1., 1.])

In [0]:
a[1]

tensor(1.)

In [0]:
float(a[1])

1.0

In [0]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [0]:
# triangle 2D coordinates
points = torch.zeros(6)
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

In [0]:
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
points

tensor([1., 4., 2., 1., 3., 5.])

In [0]:
# coordinates of the first point
float(points[0]), float(points[1])

(1.0, 4.0)

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [0]:
points.shape

torch.Size([3, 2])

In [0]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [0]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [0]:
points[0, 1]

tensor(4.)

In [0]:
points[0]

tensor([1., 4.])

## 2.2 Tensors and storages

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [0]:
# index into a storage manually
points_storage = points.storage()
points_storage[0]

1.0

In [0]:
points.storage()[1]

4.0

In [0]:
# changing the value of a storage, changes the content of its referring tensor
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

## 2.3 Size, storage offset, and strides

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()

2

In [0]:
second_point.size()

torch.Size([2])

In [0]:
# The size contains the same information in the shape property
second_point.shape

torch.Size([2])

In [0]:
points.stride()

(2, 1)

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.size()

torch.Size([2])

In [0]:
second_point.storage_offset()

2

In [0]:
second_point.stride()

(1,)

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [0]:
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [0]:
# verify that the two tensors share storage
id(points.storage()) == id(points_t.storage())

True

In [0]:
points.stride()

(2, 1)

In [0]:
points_t.stride()

(1, 2)

In [0]:
# transposing isn't limited to matrices
some_tensor = torch.ones(2, 4, 5)
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor.shape

torch.Size([2, 4, 5])

In [0]:
some_tensor_t.shape

torch.Size([5, 4, 2])

In [0]:
some_tensor.stride()

(20, 5, 1)

In [0]:
some_tensor_t.stride()

(1, 5, 20)

In [0]:
points.is_contiguous()

True

In [0]:
points_t.is_contiguous()

False

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [0]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [0]:
points_t.stride()

(1, 2)

In [0]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [0]:
points_t_cont.stride()

(3, 1)

In [0]:
points_t_cont.storage()

 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]

## 2.4 Numeric types

In [0]:
# to allocate a tensor of the right numeric type, you specify it in constructor
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [0]:
# find out about dtype accessing the corresponding attribute
short_points.dtype

torch.int16

In [0]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [0]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(torch.short)

In [0]:
points = torch.randn(10, 2)
short_points = points.type(torch.short)

## 2.5 Indexing tensors

In [0]:
some_list = list(range(6))

In [0]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [0]:
some_list[1:4]

[1, 2, 3]

In [0]:
some_list[1:]

[1, 2, 3, 4, 5]

In [0]:
some_list[:4]

[0, 1, 2, 3]

In [0]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [0]:
some_list[1:4:2]

[1, 3]

In [0]:
points[1:]

tensor([[2., 1.],
        [3., 5.]])

In [0]:
points[1:, :]

tensor([[2., 1.],
        [3., 5.]])

In [0]:
points[1:, 0]

tensor([2., 3.])

## 2.6 NumPy interoperatiblity

In [0]:
points = torch.ones(3,4)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [0]:
# step further like that
points_np[0, 0] = 0
# checking for the change in the tensor
points

tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [0]:
# conversely
points = torch.from_numpy(points_np)

## 2.7 Serializing tensors

In [0]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [0]:
# pickles under the hood to serialize the tensor object
torch.save(points, 'drive/My Drive/dl-pytorch/ourpoints.t')

In [0]:
!ls "drive/My Drive/dl-pytorch"

ourpoints.t


In [0]:
with open('drive/My Drive/dl-pytorch.t', 'wb') as f:
  torch.save(points, f)

In [0]:
points = torch.load('drive/My Drive/dl-pytorch/ourpoints.t')

In [0]:
with open('drive/My Drive/dl-pytorch.t', 'rb') as f:
  points = torch.load(f)

In [0]:
# for interoperability
import h5py

In [0]:
f = h5py.File('drive/My Drive/dl-pytorch/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [0]:
f = h5py.File('drive/My Drive/dl-pytorch/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[1:]

In [0]:
last_points = torch.from_numpy(dset[1:])
f.close()

## 2.8 Moving tensors to the GPU

In [0]:
# create tensor on the GPU by specifying the device
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]], device='cuda')

In [0]:
# copy a tensor from CPU to GPU
points_gpu = points.to(device='cuda')

In [0]:
# in case the machine has more than one GPU
points_gpu = points.to(device='cuda:0')

In [0]:
points = 2 * points

In [0]:
points_gpu = 2 * points.to(device='cuda')

In [0]:
# still performed on the GPU
points_gpu = points_gpu + 4

In [0]:
# move tensor back to the CPU
points_cpu = points_gpu.to(device='cpu')

In [0]:
# shorthand methods
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

## 2.9 The tensor API

In [0]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

In [0]:
a_t = a.transpose(0, 1)

In [0]:
a = torch.ones(3,2)

In [0]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [0]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Exercises

In [0]:
a = torch.tensor(list(range(9)))

In [0]:
a.size()

torch.Size([9])

In [0]:
a.storage_offset()

0

In [0]:
a.stride()

(1,)

In [0]:
a.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]

In [0]:
b = a.view(3, 3)
b[1, 1]

tensor(4)

In [0]:
c = b[1:, 1:]
c

tensor([[4, 5],
        [7, 8]])

In [0]:
c.size()

torch.Size([2, 2])

In [0]:
c.storage_offset()

4

In [0]:
c.stride()

(3, 1)

In [0]:
a = torch.FloatTensor([1.0, -0.5, 3.4, -2.1, 0.0, -6.5])
b = torch.cos(a)
print(b)

tensor([ 0.5403,  0.8776, -0.9668, -0.5048,  1.0000,  0.9766])


In [0]:
a

tensor([ 1.0000, -0.5000,  3.4000, -2.1000,  0.0000, -6.5000])

In [0]:
a.cos_()

tensor([ 0.5403,  0.8776, -0.9668, -0.5048,  1.0000,  0.9766])

In [0]:
a

tensor([ 0.5403,  0.8776, -0.9668, -0.5048,  1.0000,  0.9766])