<a href="https://colab.research.google.com/github/ibacaraujo/deep-learning-with-pytorch/blob/master/ch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 2

## 2.1 Tensor fundamentals

In [0]:
import torch
a = torch.ones(3)

In [0]:
a

tensor([1., 1., 1.])

In [0]:
a[1]

tensor(1.)

In [0]:
float(a[1])

1.0

In [0]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [0]:
# triangle 2D coordinates
points = torch.zeros(6)
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

In [0]:
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
points

tensor([1., 4., 2., 1., 3., 5.])

In [0]:
# coordinates of the first point
float(points[0]), float(points[1])

(1.0, 4.0)

In [0]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [0]:
points.shape

torch.Size([3, 2])

In [0]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [0]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [0]:
points[0, 1]

tensor(4.)

In [0]:
points[0]

tensor([1., 4.])

## 2.2 Tensors and storages

In [3]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [4]:
# index into a storage manually
points_storage = points.storage()
points_storage[0]

1.0

In [5]:
points.storage()[1]

4.0

In [6]:
# changing the value of a storage, changes the content of its referring tensor
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])